version: '3.9'

services:
  #  web:
  #    build:
  #      context: ./
  #      dockerfile: ./apps/front/Dockerfile
  #    ports:
  #      - '4200:80'
  #    restart: on-failure
  #    depends_on:
  #      - api
  api:
    environment:
      DATABASE_URL: ${ISPENT_POSTGRES_URL_DOCKER}

volumes:
  postgres-data:
