version: '3.9'

services:
  api:
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '3333:3333'
    environment:
      FIREBASE_PROJECT_ID: ${ISPENT_FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY: ${ISPENT_FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${ISPENT_FIREBASE_CLIENT_EMAIL}
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${ISPENT_POSTGRES_PASS}
      POSTGRES_DB: 'ispent'

volumes:
  postgres-data:
